name: master

on:
  push:
    branches:
      - master
      - customization

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '2.1.202'
    - name: Build library (.net core)
      run: dotnet build src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj --configuration release
    - name: Build and run .net core tests
      run: |
        dotnet build src/MIDTesters.Core/MIDTesters.Core.csproj
        dotnet test src/MIDTesters.Core/MIDTesters.Core.csproj
    - uses: nuget/setup-nuget@v1
    - name: Publish NuGet Package
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet build src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj --configuration release
        nuget push src/OpenProtocolInterpreter/bin/release/OpenProtocolInterpreter.3.2.2.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
