name: .Net Framework

on: 
  pull_request:
    paths:
      - 'src/*'
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: msbuild src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj -p:Configuration=Release
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/setup-dotnet@v1
      - name: build
        run: msbuild src/MIDTesters/MIDTesters.csproj
      - name: test
        run: vstest.console src/MIDTesters/bin/Debug/MIDTesters.dll